booking/urls.py
from django.urls import path
from booking import views

# Define the application namespace
app_name = "booking"

# URL patterns for the booking app
urlpatterns = [
    # URL pattern for checking room availability
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    
    # URL pattern for adding a room to selection
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
   
    # URL pattern for deleting a room from selection
    path("delete_selection/", views.delete_selection, name="delete_selection")
]

hms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Custom URls
    path("user/", include("userauths.urls")),
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("dashboard/", include("user_dashboard.urls")),

    # CK Editor
    path("ckeditor5/", include("django_ckeditor_5.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from hotel import views

# Define the application namespace
app_name = "hotel"

# URL patterns for the hotel app
urlpatterns = [
    # URL pattern for the index view
    path("", views.index, name="index"),
    
    # URL pattern for the hotel detail view
    path("detail/<slug>/", views.hotel_detail, name="hotel_detail"),
    
    # URL pattern for the room type detail view
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    
    # URL pattern for the selected rooms view
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),

    # URL pattern for checkout
    path("checkout/<booking_id>/ ", views.checkout, name="checkout"),
    
    # URL pattern for room update
    path("update_room_status/", views.update_room_status, name="update_room_status"),

    # URL pattern for the payment success
    path("success/<booking_id>/", views.payment_success, name="payment_success"),
    
    # URL pattern for the payment failure
    path("failed/<booking_id>/", views.payment_failed, name="payment_failed"),
]

hotel/views.py
import datetime
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from hotel.models import Hotel, Booking, Room, RoomType, Coupon
from userauths.models import Profile
from decimal import Decimal
from django.utils import timezone
from django.http import HttpResponse



# Display the list of live hotels on the index page
def index(request):
    hotels = Hotel.objects.filter(status="Live")
    context = {
        "hotels": hotels
    }
    return render(request, "hotel/hotel.html", context)

# Display the list of featured  hotel
def hotel_list(request):
    featured_hotels = Hotel.objects.filter(featured=True)[:3]
    return render(request, 'hotel/hotel.html', {'hotels': featured_hotels})

def profile(request):
    profile = Profile.objects.get(user=request.user)
    
    context = {
        "profile": profile
    }
    return render(request, "hotel/hotel.html", context)


# Display details of a specific hotel
def hotel_detail(request, slug):
    # Retrieve a single live hotel by slug
    hotel = Hotel.objects.get(status="Live", slug=slug)
    context = {
        "hotel": hotel,
    }
    return render(request, "hotel/hotel_detail.html", context)

# Display details of a specific room type in a hotel
def room_type_detail(request, slug, rt_slug):
    # Retrieve the hotel and room type objects based on slugs
    hotel = Hotel.objects.get(status="Live", slug=slug)
    room_type = RoomType.objects.get(hotel=hotel, slug=rt_slug)
    rooms = Room.objects.filter(room_type=room_type, is_available=True)

    # Get query parameters from the URL
    id = request.GET.get("hotel-id")
    checkin = request.GET.get("checkin")
    checkout = request.GET.get("checkout")
    adult = request.GET.get("adult")
    children = request.GET.get("children")

    context = {
        "hotel": hotel,
        "room_type": room_type,
        "rooms": rooms,
        "checkin": checkin,
        "checkout": checkout,
        "adult": adult,
        "children": children,
    }

    return render(request, "hotel/room_type_detail.html", context)

# Display the selected rooms and calculate the total cost
def selected_rooms(request):
    total = 0
    room_count = 0
    total_days = 0
    adult = 0
    children = 0
    checkin = ""
    checkout = ""

    if 'selection_data_obj' in request.session:

        if request.method == "POST":
            for h_id, item in request.session['selection_data_obj'].items():
                # Execute code on submission
                id = int(item['hotel_id'])
                checkin = item['checkin']
                checkout = item['checkout']
                adult = int(item['adult'])  
                children = int(item['children'])
                room_type_ = int(item['room_type'])
                room_id = int(item['room_id'])
                room_type = RoomType.objects.get(id=room_type_)

                user = request.user
                hotel = Hotel.objects.get(id=id)
                room = Room.objects.get(id=room_id)
                room_type = RoomType.objects.get(id=room_type_)
            
            # Debugging: Log the session data
            # print(f"Check-in date from session: {checkin}")
            # print(f"Check-out date from session: {checkout}")

            # Calculate total booked days
            date_format = "%Y-%m-%d"
            checkin_date = datetime.datetime.strptime(checkin, date_format)
            checkout_date = datetime.datetime.strptime(checkout, date_format)
            time_difference = checkout_date - checkin_date
            total_days = time_difference.days

            full_name = request.POST.get('full_name')
            email = request.POST.get('email')
            phone = request.POST.get('phone')

            booking = Booking.objects.create(
                hotel=hotel,
                room_type=room_type,
                check_in_date=checkin,
                check_out_date=checkout,
                total_days=total_days,
                num_adults=adult,
                num_children=children,
                full_name=full_name,
                email=email,
                phone=phone,
                user=request.user or None,
                payment_status="processing",
            )
 
            for h_id, item in request.session['selection_data_obj'].items():
                room_id = int(item["room_id"])
                room = Room.objects.get(id=room_id)
                booking.room.add(room)

                room_count += 1
                days = total_days
                price = room_type.price
                room_price = price * room_count
                total = room_price * days
            
            booking.total += float(total)
            booking.before_discount += float(total)
            booking.save()

            return redirect("hotel:checkout", booking.booking_id)


        hotel = None
        for h_id, item in request.session['selection_data_obj'].items():
            id = int(item['hotel_id'])
            checkin = item['checkin']
            checkout = item['checkout']
            adult = int(item['adult'])  
            children = int(item['children'])
            room_type_ = int(item['room_type'])
            room_id = int(item['room_id'])
            room_type = RoomType.objects.get(id=room_type_)
            
            # Debugging: Log the session data
            # print(f"Check-in date from session: {checkin}")
            # print(f"Check-out date from session: {checkout}")

            date_format = "%Y-%m-%d"
            checkin_date = datetime.datetime.strptime(checkin, date_format)
            checkout_date = datetime.datetime.strptime(checkout, date_format)
            time_difference = checkout_date - checkin_date
            total_days = time_difference.days

            room_count += 1
            days = total_days
            price = room_type.price

            room_price = price * room_count
            total = room_price * days

            hotel = Hotel.objects.get(id=id)
        
        context = {
            "data": request.session['selection_data_obj'],
            "total_selected_items": len(request.session['selection_data_obj']),
            "total": total,
            "total_days": total_days,
            "adult": adult,
            "children": children,
            "checkin": checkin,
            "checkout": checkout,
            "hotel": hotel,
        }
        return render(request, "hotel/selected_rooms.html", context)
    else:
        messages.warning(request, "No selected room yet")
        return redirect("/")


# Calculate total payable amount with or without coupon
def checkout(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id)
    if request.method == "POST":
            code = request.POST.get('code')
            try:
                coupon = Coupon.objects.get(code__iexact=code, active=True)
                if coupon in booking.coupons.all():
                    messages.warning(request, "Coupon already applied to this booking.")
                    return redirect("hotel:checkout", booking.booking_id)
                
                else:
                    if coupon.type == "Percentage":
                        discount = booking.total * (coupon.discount / 100)
                    else:
                        discount = coupon.discount

                    booking.coupons.add(coupon)
                    booking.total -= discount
                    booking.saved += discount
                    booking.save()

                    messages.success(request, "Coupon applied successfully.")
                    return redirect("hotel:checkout", booking.booking_id)
  
            except:
                messages.warning(request, "Invalid Coupon Code")
                # print("coupon does note exist")
    context = {
        "booking": booking
    }

    return render(request,"hotel/checkout.html", context)

def payment_success(request, booking_id):
    successID = request.GET.get('successID')
    booking_total = request.GET.get('booking_total')

    if successID and booking_total:
        successID = successID.rstrip("/")
        # booking_total = booking_total.rstrip("/")

        booking = Booking.objects.get(booking_id=booking_id,successID=successID)

        # if booking.total == booking_total:
            # messages.success(request, "payment successfull") 
        if booking.payment_status == "processing":
            booking.payment_status = "paid"
            booking.is_active = True
            booking.save()

            # Future update
            # notify = Notification.objects.create(booking=booking, message="Payment Successful")

            # Clear cart
            if 'selection_data_obj' in request.session:
                del request.session['selection_data_obj']

        else:
            messages.success(request, "Payment already processed for this booking.")
            return redirect("/")

    else:
        messages.error(request, "Payment Failed to Match. Manipulation, is that you 😜?")

    context = {
        "booking": booking
    }
    return render(request, "hotel/payment_success.html", context)

def payment_failed(request, booking_id):
    return render(request, "hotel/payment_failed.html", {"booking_id": booking_id})

def update_room_status(request):
    today =timezone.now().date()
    
    booking = Booking.objects.filter(is_active=True, payment_status="paid")
    
    # Checkin processes
    for b in booking:
        # if user books a future date, the room will remain available till then
        if b.checked_in_tracker != True:
            if b.check_in_date > today:
                b.checked_in_tracker = False
                b.checked_in = False
                b.save()

                for r in b.room.all():
                    r.is_available = True
                    r.save()
            
            # the room is not available

templates/hotel/hotel.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<style>
  .headline{
    
    font-weight:900; 
    text-shadow: rgba(255,255,255,1) 0px 0px 50px;
  }
</style>
<!-- Banner -->
<div class="search_container_block main_search_block" data-background-image="images/home_section_1.jpg">
  <div class="main_inner_search_block">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="dm-sans headline" style="font-size: 100px; ">HOMIFICE</h2>
          <h2>Streamlining Operations for <br>Hoteliers & Guests</h2>
          <h4></h4>
          </div>
      </div>
    </div>
  </div>
</div>

<!-- Set Featured List first -->

<section class="fullwidth_block padding-top-50 padding-bottom-70" data-background-color="#f9f9f9">
  <div class="container">
    <div class="row slick_carousel_slider">
      <div class="col-md-12">
        <h3 class="headline_part centered margin-bottom-45">Top Featured Locations <span>Explore the greatest places in the
            city</span> </h3>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="simple_slick_carousel_block utf_dots_nav">
            {% for hotel in hotels %}
                <div class="utf_carousel_item">
                    <a href="{% url 'hotel:hotel_detail' hotel.slug %}" class="utf_listing_item-container compact">
                        <div class="utf_listing_item">
                            <img src="{{hotel.image.url}}" width="400%" height="" alt="">
                            <span class="featured_tag">Featured</span>
                            <span class="utf_open_now">Open Now</span>
                            <div class="utf_listing_item_content">
                                <div class="utf_listing_prige_block"></div>
                                <h3>{{hotel.name}}</h3>
                                <span><i class="fa fa-map-marker"></i> {{ hotel.address }}</span>
                                <span><i class="fa fa-phone"></i> {{hotel.mobile}} </span>
                                <span><i class="fa fa-envelope"></i> {{hotel.email}} </span>
                            </div>
                        </div>
                        <div class="utf_star_rating_section" data-rating="4.5">
                            <div class="utf_counter_star_rating">(4.5)</div>
                            <span class="utf_view_count"><i class="fa fa-eye"></i>{{ hotel.views }}</span>
                            <span class="like-icon"></span>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="fullwidth_block search_categorie_block">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="headline_part centered margin-top-75 margin-bottom-45">World Class Clasic Hotels <span>Recommended For You
            </span> </h3>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="container">
      <div class="row">

        {% for hotel in hotels %}
        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="category_container_item_part">
            <a href="{% url 'hotel:hotel_detail' hotel.slug %}" class="category_item_box">
              <div class="featured-type featured">
                Latest
              </div>
              <img src="{{hotel.image.url}}" alt="" />
              <span class="category_item_box_btn">Browse</span>
              <div class="category_content_box_part">
                <h3>{{hotel.name}}</h3>
                <span>{{hotel.name}}</span>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}

        
      </div>
    </div>
  </div>
</div>
<div class="clearfix"></div>



<section class="fullwidth_block padding-bottom-75">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2 class="headline_part centered margin-top-80">How Homifice Works <span class="margin-top-10">Discover & connect
            with great local businesses</span> </h2>
      </div>
    </div>
    <div class="row container_icon">
      <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="box_icon_two box_icon_with_line"> <i class="im im-icon-Map-Marker2"></i>
          <h3>Find Interesting Place</h3>
          <p>Discover unique destinations and hidden gems with our extensive database of interesting places. Whether you're looking for a serene beach, a bustling city, or a quaint village, we have something for everyone. Explore new cultures, enjoy local cuisines, and create unforgettable memories on your next adventure.</p>
        </div>
      </div>

      <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="box_icon_two box_icon_with_line"> <i class="im im-icon-Mail-Add"></i>
          <h3>Contact Hotel Admins</h3>
          <p>Reach out to property owners directly and get the information you need to make an informed decision. Our platform makes it easy to connect with owners, ask questions, and discuss any specific requirements you might have. Establish a direct line of communication to ensure your stay is perfectly tailored to your needs..</p>
        </div>
      </div>

      <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="box_icon_two"> <i class="im im-icon-Administrator"></i>
          <h3>Make a Reservation</h3>
          <p>Secure your accommodation effortlessly through our user-friendly reservation system. Simply choose your preferred dates, select your desired property, and complete your booking in just a few clicks. Enjoy peace of mind with instant confirmation and prepare for a stress-free stay at your chosen destination.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="utf_testimonial_part fullwidth_block padding-top-75 padding-bottom-75 utf_cta_area2_block">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h3 class="headline_part centered"> What Our Customers Say <span class="margin-top-15">Homifice has revolutionized accommodation for travelers, making reservations seamless and hassle-free. Here's what our satisfied customers have to say...</span> </h3>
      </div>
    </div>
  </div>
  <div class="fullwidth_carousel_container_block margin-top-20">
    <div class="utf_testimonial_carousel testimonials">
      <div class="utf_carousel_review_part">
        <div class="utf_testimonial_box">
          <div class="testimonial">"Homifice made my travel experience so much better! Finding the perfect place to stay was quick and easy, and the reservation process was a breeze. Highly recommend!"</div>
        </div>
        <div class="utf_testimonial_author"> <img src="images/happy-client-01.jpg" alt="">
          <h4>Denwen Evil <span>Web Developer</span></h4>
        </div>
      </div>
      <div class="utf_carousel_review_part">
        <div class="utf_testimonial_box">
          <div class="testimonial">"As a frequent traveler, I appreciate how Homifice simplifies finding and booking accommodations. The platform is user-friendly and the customer service is excellent!"</div>
        </div>
        <div class="utf_testimonial_author"> <img src="images/happy-client-02.jpg" alt="">
          <h4>Adam Alloriam <span>Web Developer</span></h4>
        </div>
      </div>
      <div class="utf_carousel_review_part">
        <div class="utf_testimonial_box">
          <div class="testimonial">"Homifice takes the stress out of planning trips. Their comprehensive listings and easy reservation system ensure that I always find a great place to stay, no matter where I'm headed."</div>
        </div>
        <div class="utf_testimonial_author"> <img src="images/happy-client-03.jpg" alt="">
          <h4>Illa Millia <span>Project Manager</span></h4>
        </div>
      </div>
      <div class="utf_carousel_review_part">
        <div class="utf_testimonial_box">
          <div class="testimonial">"I've been using Homifice for all my travel accommodations and couldn't be happier. The ease of use and reliability of the platform make it my go-to choice every time."</div>
        </div>
        <div class="utf_testimonial_author"> <img src="images/happy-client-01.jpg" alt="">
          <h4>Denwen Evil <span>Web Developer</span></h4>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/hotel/hotel_detail.html
<!-- Template Inheritance -->
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<div id="utf_listing_gallery_part" class="utf_listing_section">
    <div class="utf_listing_slider utf_gallery_container margin-bottom-0">

        {% for gallery_images in hotel.hotel_gallery.all %}
        <a href="{{ gallery_images.image.url }}" data-background-image="{{ gallery_images.image.url }}"
            class="item utf_gallery"></a>
        {% endfor %}
    </div>
</div>
<div class="container">
    <div class="row utf_sticky_main_wrapper">
        <div class="col-lg-8 col-md-8">
            <div id="titlebar" class="utf_listing_titlebar">
                <div class="utf_listing_titlebar_title">
                    <h1>{{hotel.name}}</h1>
                    <span> <a href="#utf_listing_location" class="listing-address"> <i class="sl sl-icon-location"></i>
                            {{hotel.address}}</a> </span>
                    <span class="call_now"><i class="sl sl-icon-phone"></i> {{hotel.mobile}} </span>
                    <div class="utf_star_rating_section" data-rating="4.5">
                        <div class="utf_counter_star_rating">(4.5) / (14 Reviews)</div>
                    </div>
                    
                </div>
            </div>
            <div id="utf_listing_overview" class="utf_listing_section">
                <h3 class="utf_listing_headline_part margin-top-30 margin-bottom-30">Description</h3>
                <p>{{ hotel.description|safe }}</p>

                <div id="utf_listing_tags"
                    class="utf_listing_section listing_tags_section margin-bottom-10 margin-top-0">
                    <a href="tel:{{hotel.mobile }}"><i class="sl sl-icon-phone"></i> {{hotel.mobile}} </a>
                    <a href="mailto:{{ hotel.email }}"><i class="fa fa-envelope-o"></i> {{hotel.email}} </a>
                    <a href="https://{{hotel.website }}"><i class="sl sl-icon-globe"></i>  {{hotel.website}} </a>
                </div>
                <div class="social-contact">
                    <a href="{{hotel.facebook}}" class="facebook-link"><i class="fa fa-facebook"></i> Facebook</a>
                    <a href="{{hotel.twitter}}" class="twitter-link"><i class="fa fa-twitter"></i> Twitter</a>
                    <a href="{{hotel.instagram}}" class="instagram-link"><i class="fa fa-instagram"></i> Instagram</a>
                    <a href="{{hotel.youtube}}" class="youtube-link"><i class="fa fa-youtube-play"></i> Youtube</a>
                </div>
            </div>

            <div id="utf_listing_tags" class="utf_listing_section listing_tags_section">
                <h3 class="utf_listing_headline_part margin-top-40 margin-bottom-40">Tags</h3>

                {% for all_tags in hotel.tags.all %}
                <a href="#"><i class="fa fa-tag" aria-hidden="true"></i> {{ all_tags.name }}</a>
                {% endfor %}
            </div>

            <div class="utf_listing_section">
                <h3 class="utf_listing_headline_part margin-top-50 margin-bottom-40">Pricing</h3>
                <div class="show-more">
                    <div class="utf_pricing_list_section">
                        <h4>Select Pass</h4>
                        <ul>
                            {% for rooms in hotel.hotel_room_types %}
                            <li>
                                <h5>{{rooms.type}}</h5>
                                <p><strong>Price: </strong>{{rooms.price}} / Night </p>
                                <p><strong>Room Capacity: </strong>{{rooms.room_capacity}} People </p>
                                <p><strong>Number of Beds: </strong>{{rooms.number_of_beds}} </p>
                                <p><a href="{% url 'hotel:room_type_detail' rooms.hotel.slug rooms.slug%}"
                                        class="text-muted">View More <i class="fas fa-link"></i></a></p>
                                <span>{{rooms.price}}</span>
                            </li>

                            {% endfor %}

                        </ul>
                    </div>
                </div>
                <a href="#" class="show-more-button" data-more-title="Show More" data-less-title="Show Less"><i
                        class="fa fa-angle-double-down"></i></a>
            </div>
        </div>

        <!-- Sidebar -->
        <div class="col-lg-4 col-md-4 margin-top-75 sidebar-search">
            <div class="verified-badge with-tip margin-bottom-30"
                data-tip-content="Purchase ticket has been verified and belongs business owner or manager."> <i
                    class="sl sl-icon-check"></i> Now Available</div>
                    <div class="utf_box_widget booking_widget_box shadow-lg ">
                        <h3><i class="fa fa-calendar"></i> Check Room Availability</h3>
                        <form class="row with-forms margin-top-0" method="POST" action="{% url 'booking:check_room_availability' %}">
                            {% csrf_token %}
                            <input type="hidden" name="hotel-id" value="{{hotel.id}}">
                
                            <div class="select_date_box">
                              <label for="checkin">Check-in Date</label>
                              <input type="date" class="date-pick_1" name="checkin" id="checkin" ="Select Date">
                            </div>
                
                            <div class="select_date_box">
                              <label for="checkout">Check-out Date</label>
                              <input type="date" class="date-pick_2" id="checkout" name="checkout" placeholder="Select Date">
                            </div>
                
                            <div class="with-forms ">
                              <div class="col-lg-12">
                                <a href="#" class="qtyTotal" style="visibility: hidden;">Guests</a>
                                <div class="panel-dropdown-content">
                                  <div class="qtyButtons">
                                    <div class="qtyTitle">Adults</div>
                                    <input type="text" class="qtyInput" name="adult" value="1">
                                  </div>
                                  <div class="qtyButtons">
                                    <div class="qtyTitle">Children</div>
                                    <input type="text" class="qtyInput" name="children" value="0">
                                  </div>
                                </div>
                              </div>
                            </div>
                
                            <div class="with-forms margin-top-30">
                              <a href="#">Select Room Type</a>
                              <select name="room_type" class="utf_chosen_select_single" required id="">
                                {% for r in hotel.hotel_room_types %}
                                <option value="{{r.slug}}">{{r.type}}</option>
                                {% endfor %}
                              </select>
                            </div>
                            <button class="like-button add_to_wishlist"><span class="like-icon"></span> Add to Wishlist</button>
                            <button type="submit" class="utf_progress_button button fullwidth_block margin-top-5">Check
                              Availability</button>
                          </form>
              
                        <div class="clearfix"></div>
                      </div>
            
            <div class="opening-hours margin-top-35">
                <div class="utf_coupon_widget" style="background-image: url(images/coupon-bg-1.jpg);">
                    <div class="utf_coupon_overlay"></div>
                    <a href="#" class="utf_coupon_top">
                        <h3>Book Now & Get 50% Discount</h3>
                        <div class="utf_coupon_expires_date">Date of Expires 05/08/2022</div>
                        <div class="utf_coupon_used"><strong>How to use?</strong> Just show us this coupon on a screen
                        </div>
                    </a>
                    <div class="utf_coupon_bottom">
                        <p>Coupon Code</p>
                        <div class="utf_coupon_code">DL76T</div>
                    </div>
                </div>
            </div>

            
           
            <div class="utf_box_widget opening-hours review-avg-wrapper margin-top-35">
                <h3><i class="sl sl-icon-star"></i> Rating Average </h3>
                <div class="box-inner">
                    <div class="rating-avg-wrapper text-theme clearfix">
                        <div class="rating-avg">4.8</div>
                        <div class="rating-after">
                            <div class="rating-mode">/5 Average</div>

                        </div>
                    </div>
                    <div class="ratings-avg-wrapper">
                        <div class="ratings-avg-item">
                            <div class="rating-label">Quality</div>
                            <div class="rating-value text-theme">5.0</div>
                        </div>
                        <div class="ratings-avg-item">
                            <div class="rating-label">Location</div>
                            <div class="rating-value text-theme">4.5</div>
                        </div>
                        <div class="ratings-avg-item">
                            <div class="rating-label">Space</div>
                            <div class="rating-value text-theme">3.5</div>
                        </div>
                        <div class="ratings-avg-item">
                            <div class="rating-label">Service</div>
                            <div class="rating-value text-theme">4.0</div>
                        </div>
                        <div class="ratings-avg-item">
                            <div class="rating-label">Price</div>
                            <div class="rating-value text-theme">5.0</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Limit booking to present or future date -->
<script>
    const today = new Date()
    const formatToday = today.toISOString().split('T')[0];
    console.log(formatToday);
    document.querySelector(".date-pick_1").min = formatToday;
    document.querySelector(".date-pick_2").min = formatToday;
</script>

{% endblock content %}