hms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Custom URls
    path("user/", include("userauths.urls")),
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("dashboard/", include("user_dashboard.urls")),

    # CK Editor
    path("ckeditor5/", include("django_ckeditor_5.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from hotel import views

# Define the application namespace
app_name = "hotel"

# URL patterns for the hotel app
urlpatterns = [
    # URL pattern for the index view
    path("", views.index, name="index"),
    
    # URL pattern for the hotel detail view
    path("detail/<slug>/", views.hotel_detail, name="hotel_detail"),
    
    # URL pattern for the room type detail view
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    
    # URL pattern for the selected rooms view
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),

    # URL pattern for checkout
    path("checkout/<booking_id>/ ", views.checkout, name="checkout"),
    
    # URL pattern for room update
    path("update_room_status/", views.update_room_status, name="update_room_status"),

    # URL pattern for the payment success
    path("success/<booking_id>/", views.payment_success, name="payment_success"),
    
    # URL pattern for the payment failure
    path("failed/<booking_id>/", views.payment_failed, name="payment_failed"),
]

user_dashboard/urls.py
from django.urls import path
from user_dashboard import views

app_name = 'user_dashboard'


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path("booking_detail/<booking_id>", views.booking_detail, name="booking_detail"),
    path("bookings/", views.bookings, name="bookings"),
    path("profile/", views.profile, name="profile"),
]

userauths/urls.py
from django.urls import path
from userauths import views

# Define the application namespace
app_name = "userauths"

# URL patterns for the userauths app
urlpatterns = [
    # URL pattern for user registration
    path("sign-up/", views.RegisterView, name="sign-up"),
    
    # URL pattern for user login
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    
    # URL pattern for user logout
    path("sign-out/", views.LogoutView, name="sign-out"),
]

templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta name="author" content="">
    <meta name="description" content="">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homifice | Streamlining Operations for Hoteliers & Guests</title>
    <base href="{% static '/' %}">
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'css/mmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" id="colors">
    <!-- Include JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Sweet Alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Google Font -->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:300,400,600,700,800&amp;display=swap&amp;subset=latin-ext,vietnamese"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap" rel="stylesheet">
</head>

<body class="header-one">


    <!-- Wrapper -->
    <div id="main_wrapper">
        <header id="header_part" class="fullwidth">
            <div id="header">
                <div class="container">
                    <div class="utf_left_side">
                        <div id="logo"> <a href="/"><img src="{% static 'images/logo.png' %}" alt=""></a>
                        </div>
                        <div class="mmenu-trigger">
                            <button class="hamburger utfbutton_collapse" type="button">
                                <span class="utf_inner_button_box">
                                    <span class="utf_inner_section"></span>
                                </span>
                            </button>
                        </div>
                 
                        <div class="clearfix"></div>
                    </div>
                    <div class="utf_right_side">
                        <div class="header_widget">

                            {% if user.is_authenticated %}
                            <a href="{% url 'hotel:selected_rooms'%}" class="button border with-icon"><i class="fa fa-bed"></i><span>{{request.session.selection_data_obj|length}}</span></a> &nbsp;
                            <!-- <a href="#" class="button border with-icon"><i class="sl sl-icon-user"></i> Dashboard </a> -->
                            <!-- <a href="{% url 'userauths:sign-out' %}" class="button border sign-out"><i class="fa fa-sign-out"></i> Sign Out</a> -->
                            <div class="utf_user_menu">
                                <div class="utf_user_name"><span><img src="{% if userD.profile_image %}{{ userD.profile_image.url }}{% else %}{% static 'images/default.jpg' %}{% endif %}"
                                    alt="Profile Image"></span></div>:
                                <ul>
                                  <li><a href="{% url 'user_dashboard:dashboard' %}"><i class="sl sl-icon-layers"></i>Dashboard </a></li>
                                  <li><a href="{% url 'user_dashboard:profile' %}"><i class="sl sl-icon-user"></i> My Profile</a></li>
                                  <li><a href="{% url 'userauths:sign-out' %}"><i class="sl sl-icon-power"></i> Logout</a></li>
                                </ul>
                              </div>
                            {% else %}
                            <a href="{% url 'userauths:sign-in' %}" class="button border sign-in"><i class="fa fa-sign-in"></i> Sign In</a>
                            <a href="{% url 'userauths:sign-up' %}" class="button border with-icon"><i class="sl sl-icon-user"></i> Register </a>
                            
                            {% endif %}
                        </div>
                    </div>

                    
                </div>
            </div>
        </header>
        <div class="clearfix"></div>
        {% block content %}



        {% endblock content %}
<!-- <hr> -->
   <!-- Footer -->
   <!-- <hr style="border:1px solid rgb(252, 103, 49)"> -->
   <div id="footer" class="footer_sticky_part">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h4>About Us</h4>
                <p>At Homifice, we believe in making travel and accommodation seamless and enjoyable. Our innovative Hotel Management Software is designed to help users find and secure comfortable, reliable accommodations with ease. Whether you're traveling for business or leisure, Homifice ensures that your stay feels like a home away from home. We are committed to providing excellent service, comprehensive listings, and a user-friendly platform to meet all your accommodation needs.</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="footer_copyright_part">Copyright © 2024 All Rights Reserved | Developed by Olawuni Emmanuel Kayode</div>
            </div>
        </div>
    </div>
</div>
<div id="bottom_backto_top"><a href="#"></a></div>

    </div>
  
<!-- Loop messages -->
    <script>
        {% for message in messages  %}
            Swal.fire({
                icon: "{{message.tags}}",
                title: "{{message}}",
                timer: 1500
            })
        {% endfor %}
    </script>
    
    <!-- Scripts -->
        <script src="{% static 'scripts/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'scripts/chosen.min.js' %}"></script>
        <script src="{% static 'scripts/slick.min.js' %}"></script>
        <script src="{% static 'scripts/quantityButtons.js' %}"></script>
        <script src="{% static 'scripts/rangeslider.min.js' %}"></script>
        <script src="{% static 'scripts/magnific-popup.min.js' %}"></script>
        <script src="{% static 'scripts/jquery-ui.min.js' %}"></script>
        <script src="{% static 'scripts/bootstrap-select.min.js' %}"></script>
        <script src="{% static 'scripts/mmenu.js' %}"></script>
        <script src="{% static 'scripts/tooltips.min.js' %}"></script>
        <script src="{% static 'scripts/jquery_custom.js' %}"></script>
        <script src="{% static 'scripts/typed.js' %}"></script>
        <script src="{% static 'scripts/custom.js' %}"></script>
        <script>
            var typed = new Typed('.typed-words', {
                strings: ["Book", " Restaurants", " Hotels"],
                typeSpeed: 80,
                backSpeed: 80,
                backDelay: 4000,
                startDelay: 1000,
                loop: true,
                showCursor: true
            });
        </script>

        
</body>

</html>

templates/partials/dashboard_base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta name="author" content="">
  <meta name="description" content="">
  <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Homifice | Comfortable Smart Homes </title>
  <base href="{% static '/' %}">
  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.png">
  <!-- Style CSS -->
  <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
  <link rel="stylesheet" href="{% static 'css/mmenu.css' %}">
  <link rel="stylesheet" href="{% static 'css/perfect-scrollbar.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" id="colors">
  <!-- Google Font -->
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:300,400,600,700,800&amp;display=swap&amp;subset=latin-ext,vietnamese"
    rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800" rel="stylesheet"
    type="text/css">
</head>

<body>

  <!-- Preloader Start -->
  <!-- <div class="preloader">
    <div class="utf-preloader">
        <span></span>
        <span></span>
        <span></span>
    </div>
</div> -->
  <!-- Preloader End -->

  <!-- Wrapper -->
  <div id="main_wrapper">
    <header id="header_part" class="fixed fullwidth_block dashboard">
      <div id="header" class="not-sticky">
        <div class="container">
          <div class="utf_left_side">
            <div id="logo"> <a href="index_1.html"><img src="{% static 'images/logo.png' %}" alt=""></a> <a
                href="index_1.html" class="dashboard-logo"><img src="{% static 'images/logo2.png' %}" alt=""></a> </div>
            <div class="mmenu-trigger">
              <button class="hamburger utfbutton_collapse" type="button">
                <span class="utf_inner_button_box">
                  <span class="utf_inner_section"></span>
                </span>
              </button>
            </div>
            <nav id="navigation" class="style_one">
            </nav>
            <div class="clearfix"></div>
          </div>
          <div class="utf_right_side">
            <div class="header_widget">
              
              <div class="utf_user_menu">
                <div class="utf_user_name"><span><img src="{% static 'images/dashboard-avatar.jpg' %}" alt=""></span>Hi,
                  {{ request.user.email }}</div>:
                <ul>
                  <li><a href="/"><i class="sl sl-icon-layers"></i> View Site </a></li>
                  <li><a href="dashboard_my_profile.html"><i class="sl sl-icon-user"></i> My Profile</a></li>
                  <li><a href="{% url 'userauths:sign-out' %}"><i class="sl sl-icon-power"></i> Logout</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div class="clearfix"></div>

    <!-- Dashboard -->
    <div id="dashboard">

      {% include 'partials/dashboard_sidebar.html' %}
      <div class="utf_dashboard_content">
        <!-- <div> -->
          <div class="row margin-bottom-20">
            <div class="col-md-12">
              <!-- <h2>Dashboard</h2> -->
              <nav id="breadcrumbs">
                <ul>
                  <li><a href="index_1.html">Home</a></li>
                  <li>Dashboard</li>
                </ul>
              </nav>
            </div>
          </div>
        <!-- </div> -->

        <div class="row">
          <div class="col-md-12">
            <div class="notification success closeable margin-bottom-30">
              <p>Welcome Back <strong>{{ request.user.full_name }}</strong></p>
              <a class="close" href="#"></a>
            </div>
          </div>
        </div>

        {% block content %}

        {% endblock content %}

        <!-- Scripts -->
        <script src="{% static 'scripts/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'scripts/chosen.min.js' %}"></script>
        <script src="{% static 'scripts/perfect-scrollbar.min.js' %}"></script>
        <script src="{% static 'scripts/slick.min.js' %}"></script>
        <script src="{% static 'scripts/rangeslider.min.js' %}"></script>
        <script src="{% static 'scripts/magnific-popup.min.js' %}"></script>
        <script src="{% static 'scripts/jquery-ui.min.js' %}"></script>
        <script src="{% static 'scripts/mmenu.js' %}"></script>
        <script src="{% static 'scripts/tooltips.min.js' %}"></script>
        <script src="{% static 'scripts/jquery_custom.js' %}"></script>
        <script>
          (function ($) {
            try {
              var jscr1 = $('.js-scrollbar');
              if (jscr1[0]) {
                const ps1 = new PerfectScrollbar('.js-scrollbar');

              }
            } catch (error) {
              console.log(error);
            }
          })(jQuery);
        </script>

</body>

</html>

templates/partials/dashboard_sidebar.html
<a href="#" class="utf_dashboard_nav_responsive"><i class="fa fa-reorder"></i> Dashboard Sidebar Menu</a>
    <div class="utf_dashboard_navigation js-scrollbar">
      <div class="utf_dashboard_navigation_inner_block">
        <ul>
          <li class="active"><a href="{% url 'user_dashboard:dashboard' %}"><i class="sl sl-icon-layers"></i> Dashboard</a></li>       
		  <li><a href="{% url 'user_dashboard:bookings' %}"><i class="sl sl-icon-docs"></i> All Bookings</a></li>		                               		 
		  <li><a href="{% url 'user_dashboard:profile' %}"><i class="sl sl-icon-user"></i> My Profile</a></li>
          <li><a href="{% url 'userauths:sign-out' %}"><i class="sl sl-icon-power"></i> Logout</a></li>
        </ul>
      </div>
    </div>  