booking/urls.py
from django.urls import path
from booking import views

# Define the application namespace
app_name = "booking"

# URL patterns for the booking app
urlpatterns = [
    # URL pattern for checking room availability
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    
    # URL pattern for adding a room to selection
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
   
    # URL pattern for deleting a room from selection
    path("delete_selection/", views.delete_selection, name="delete_selection")
]

hms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Custom URls
    path("user/", include("userauths.urls")),
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("dashboard/", include("user_dashboard.urls")),

    # CK Editor
    path("ckeditor5/", include("django_ckeditor_5.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_dashboard/urls.py
from django.urls import path
from user_dashboard import views

app_name = 'user_dashboard'


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path("booking_detail/<booking_id>", views.booking_detail, name="booking_detail"),
    path("bookings/", views.bookings, name="bookings"),
    path("profile/", views.profile, name="profile"),
]

booking/models.py
from django.db import models

# Create your models here.

booking/views.py
from django.template.loader import render_to_string
from django.shortcuts import render, redirect
from django.urls import reverse
from hotel.models import Hotel, Booking, ActivityLog, StaffOnDuty, Room, RoomType, HotelFaqs, HotelFeatures, HotelGallery
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import datetime

@csrf_exempt
def check_room_availability(request):
    if request.method == "POST":
        # Retrieve data from POST request
        id = request.POST.get("hotel-id")
        checkin = request.POST.get("checkin")
        checkout = request.POST.get("checkout")
        adult = request.POST.get("adult")
        children = request.POST.get("children")
        room_type = request.POST.get("room_type")

        # Get the hotel and room type objects based on the provided data
        hotel = Hotel.objects.get(id=id)
        room_type = RoomType.objects.get(hotel=hotel, slug=room_type)

        # Construct the URL with parameters for room type details
        url = reverse("hotel:room_type_detail", args=[hotel.slug, room_type.slug])
        url_with_params = f"{url}?hotel-id={id}&checkin={checkin}&checkout={checkout}&adult={adult}&children={children}&room_type={room_type}"
        
        # Redirect to the constructed URL
        return HttpResponseRedirect(url_with_params)

def add_to_selection(request):
    # Initialize room selection dictionary
    room_selection = {}
    
    # Populate the room selection dictionary with data from GET request
    room_selection[str(request.GET['id'])] = {
        'hotel_id': request.GET['hotel_id'],
        'hotel_name': request.GET['hotel_name'],
        'room_name': request.GET['room_name'],
        'room_price': request.GET['room_price'],
        'number_of_beds': request.GET['number_of_beds'],
        'room_number': request.GET['room_number'],
        'room_type': request.GET['room_type'],
        'room_id': request.GET['room_id'],
        'checkin': request.GET['checkin'],
        'checkout': request.GET['checkout'],
        'adult': request.GET['adult'],
        'children': request.GET['children']
    }

    # Create or update session for room selection
    if 'selection_data_obj' in request.session:
        if str(request.GET['id']) in request.session['selection_data_obj']:
            # Update the existing selection data with adult and children information
            selection_data = request.session['selection_data_obj']
            selection_data[str(request.GET['id'])]['adult'] = int(room_selection[str(request.GET['id'])]['adult'])
            selection_data[str(request.GET['id'])]['children'] = int(room_selection[str(request.GET['id'])]['children'])
            request.session['selection_data_obj'] = selection_data
        else:
            # Add new room selection to the existing selection data
            selection_data = request.session['selection_data_obj']
            selection_data.update(room_selection)
            request.session['selection_data_obj'] = selection_data
    else:
        # Create new session data object for room selection
        request.session['selection_data_obj'] = room_selection

    # Prepare the response data
    data = {
        "data": request.session['selection_data_obj'],
        "total_selected_items": len(request.session['selection_data_obj'])
    }

    # Return the response as JSON
    return JsonResponse(data)


# Delete Selection
def delete_selection(request):
    hotel_id = str(request.GET['id'])
    if 'selection_data_obj' in request.session:
        if hotel_id in request.session['selection_data_obj']:
            selection_data = request.session['selection_data_obj']
            del request.session['selection_data_obj'][hotel_id]
            # Update / refresh selection
            request.session['selection_data_obj'] = selection_data

        total = 0
        total_days = 0
        room_count = 0
        adult = 0
        children = 0
        checkin = ""
        checkout = ""
        hotel = None

        if 'selection_data_obj' in request.session:
            for h_id, item in request.session['selection_data_obj'].items():
            # Retrieve room selection details from session
                id = int(item['hotel_id'])
                checkin = item['checkin']
                checkout = item['checkout']
                adult = int(item['adult'])  
                children = int(item['children'])
                room_type_ = int(item['room_type'])
                room_id = int(item['room_id'])
                room_type = RoomType.objects.get(id=room_type_)
                
                # Calculate total booked days
                date_format = "%Y-%m-%d"
                checkin_date = datetime.datetime.strptime(checkin, date_format)
                checkout_date = datetime.datetime.strptime(checkout, date_format)
                time_difference = checkout_date - checkin_date
                total_days = time_difference.days

                room_count += 1
                days = total_days
                price = room_type.price

                room_price = price * room_count
                total = room_price * days
    
        context = render_to_string(
        "hotel/async/selected_rooms.html", 
            {
                "data": request.session['selection_data_obj'], 
                "total_selected_items": len(request.session['selection_data_obj']),
                "total": total,
                "total_days": total_days,
                "adult":adult,
                "children":children,
                "checkin":checkin,
                "checkout": checkout,
                "hotel":hotel,
            },
        )
    

    return JsonResponse({"data": context, "total_selected_items": len(request.session['selection_data_obj'])}) 

user_dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db import models
from hotel.models import Hotel, Booking
from userauths.models import Profile 
from userauths.forms import UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
# Create your views here.
@login_required

def dashboard(request):
    bookings = Booking.objects.filter(user=request.user, payment_status="paid") 
    total_spent = Booking.objects.filter(user=request.user, payment_status='paid').aggregate(amount=models.Sum("total"))
    total_spent_formatted = "{:.2f}".format(total_spent['amount'])  # Format to 2 decimal places

    # print(total_spent_formatted)
    context ={
        "bookings": bookings,
        "total_spent": total_spent,
        "total_spent_to_display": total_spent_formatted,  


    }
    
    return render(request, 'user_dashboard/dashboard.html', context)


@login_required
def booking_detail(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id, user=request.user, payment_status="paid")
    context = {
        "booking": booking
    }
    return render(request, "user_dashboard/booking_detail.html", context)


@login_required
def bookings(request):
    booking = Booking.objects.filter(user=request.user, payment_status="paid")
    context = {
        "booking": booking
    }
    return render(request, "user_dashboard/booking.html", context)


@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        userForm = UserUpdateForm(request.POST, instance=request.user)
        profileForm = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
            profileForm.save()
            messages.success(request, "Your profile has been updated successfully.")
            return redirect("user_dashboard:profile")
    else:
        userForm = UserUpdateForm(instance=request.user)
        profileForm = ProfileUpdateForm(instance=request.user.profile)

    context = {
        "profile": profile,
        "userForm": userForm,
        "profileForm": profileForm,
    }
    return render(request, "user_dashboard/profile.html", context)

templates/user_dashboard/booking.html
{% extends 'partials/dashboard_base.html' %}
{% load static %}
{% block content %}

<div class="row">

    <div class="col-lg-12">
        <div class="utf_dashboard_list_box margin-top-0">
            <div class="sort-by my_sort_by">
                <div class="utf_sort_by_select_item">

                </div>
            </div>
            <h4>All Bookings</h4>
            <ul>
                {% for b in booking %}
                <li class="utf_approved_booking_listing margin-bottom-10 ">
                    <div class="utf_list_box_listing_item bookings">
                        <div class="utf_list_box_listing_item-img"><img src="{{ profile.image.url }}" alt=""></div>
                        <div class="utf_list_box_listing_item_content">
                                               

                            <div class="inner">
                                <h3>{{ b.full_name|title}} <span class="utf_booking_listing_status">{{b.payment_status|title}}</span></h3>
                                <div class=""> <a href="{% url 'user_dashboard:booking_detail' b.booking_id %}" class="button gray "><i class="sl sl-icon-eye"></i> View Booking Detail</a> </div>

                                <div class="utf_inner_booking_listing_list">
                                    <h5>Hotel Name:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li>{{ b.hotel.name }}</li>
                                    </ul>
                                </div>
                                <div class="utf_inner_booking_listing_list">
                                    <h5>Hotel Address:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li>{{ b.hotel.address }}</li>
                                    </ul>
                                </div>
                                <div class="utf_inner_booking_listing_list">
                                    <h5>Hotel Email:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.hotel.email}}/li>
                                    </ul>
                                </div>

                                <div class="utf_inner_booking_listing_list">
                                    <h5>Hotel Phone:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.hotel.mobile }}</li>
                                    </ul>
                                </div>

                                <hr>
                                <div class="utf_inner_booking_listing_list">
                                    <h5>Checkin Date:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.check_in_date }}</li>
                                    </ul>
                                </div>
                                <div class="utf_inner_booking_listing_list">
                                    <h5>Checkout Date:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.check_out_date }}</li>
                                    </ul>
                                </div>
                                <div class="utf_inner_booking_listing_list">
                                    <h5>Total Days:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.total_days }}</li>
                                    </ul>
                                </div>
                                <div class="utf_inner_booking_listing_list">
                                    <h5>Booking Details:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.num_adult }} Adults</li>
                                        <li class="highlighted">{{ b.num_children }} Children</li>
                                    </ul>
                                </div>

                                <hr>
                                <div class="utf_inner_booking_listing_list">
                                    <h5>Full Name:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.full_name }}</li>
                                    </ul>
                                </div>

                                <div class="utf_inner_booking_listing_list">
                                    <h5>Email Address:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.email }}</li>
                                    </ul>
                                </div>

                                <div class="utf_inner_booking_listing_list">
                                    <h5>Phone Number:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.phone }}</li>
                                    </ul>
                                </div>


                                <div class="utf_inner_booking_listing_list">
                                    <h5>Price:-</h5>
                                    <ul class="utf_booking_listing_list">
                                        <li class="highlighted">{{ b.hotel.total }}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="col-md-12">
        <div class="footer_copyright_part">Copyright © 2022 All Rights Reserved.</div>
    </div>
</div>
</div>
</div>
</div>

{% endblock content %}

templates/user_dashboard/booking_detail.html
{% extends 'partials/dashboard_base.html' %}
{% load static %}
{% block content %}

<div class="row"> 
    <div class="col-lg-6 col-md-6">
      <div class="utf_dashboard_list_box margin-top-0">
        <h4>All Rooms <span> ( {{booking.room.all.count}} )   </span></h4>
        <ul>			  
          {% for r in booking.room.all %}
          <li class="utf_approved_booking_listing">
            <div class="utf_list_box_listing_item bookings">
              <div class="utf_list_box_listing_item-img"><img src="images/client-avatar1.jpg" alt=""></div>
              <div class="utf_list_box_listing_item_content">
                <div class="inner">
                  <h3>{{ r.room_type.type }} <span class="utf_booking_listing_status">Approved</span></h3>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Room Number</h5>
                    <ul class="utf_booking_listing_list">
                      <li>{{ r.room_number }}</li>						  						  
                    </ul>
                  </div>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Cost-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ r.room_type.price }}</li>
                    </ul>
                  </div>
                  					  					  
                </div>
              </div>
            </div>
            <!-- <div class="buttons-to-right"> <a href="#" class="button gray reject"><i class="sl sl-icon-close"></i> Cancel</a> </div> -->
          </li>
          {% endfor %}
          
        </ul>
      </div>		  
    </div>
    <div class="col-lg-6 col-md-6">
      <div class="utf_dashboard_list_box margin-top-0">
        <div class="sort-by my_sort_by">
            <div class="utf_sort_by_select_item">
             
            </div>
        </div>
        <h4>Bookings Details </h4>
        <ul>			  
          <li class="utf_approved_booking_listing">
            <div class="utf_list_box_listing_item bookings">
              <div class="utf_list_box_listing_item-img"><img src="images/client-avatar1.jpg" alt=""></div>
              <div class="utf_list_box_listing_item_content">
                <div class="inner">
                  <h3>{{ booking.full_name|title}} <span class="utf_booking_listing_status">{{ booking.payment_status|title}}</span></h3>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Hotel Name:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li>{{ booking.hotel.name }}</li>						  						  
                    </ul>
                  </div>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Hotel Address:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li>{{ booking.hotel.address }}</li>						  						  
                    </ul>
                  </div>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Hotel Email:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.hotel.email}}/li>
                    </ul>
                  </div>

                  <div class="utf_inner_booking_listing_list">
                    <h5>Hotel Phone:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.hotel.mobile }}</li>
                    </ul>
                  </div>

                  <hr>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Checkin Date:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.check_in_date }}</li>
                    </ul>
                  </div>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Checkout Date:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.check_out_date }}</li>
                    </ul>
                  </div>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Total Days:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.total_days }}</li>
                    </ul>
                  </div>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Booking Details:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.num_adult }} Adults</li>
                      <li class="highlighted">{{ booking.num_children }} Children</li>
                    </ul>
                  </div>

                  <hr>
                  <div class="utf_inner_booking_listing_list">
                    <h5>Full Name:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.full_name }}</li>
                    </ul>
                  </div>

                  <div class="utf_inner_booking_listing_list">
                    <h5>Email Address:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.email }}</li>
                    </ul>
                  </div>

                  <div class="utf_inner_booking_listing_list">
                    <h5>Phone Number:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.phone }}</li>
                    </ul>
                  </div>
                  
                  
                  <div class="utf_inner_booking_listing_list">
                    <h5>Price:-</h5>
                    <ul class="utf_booking_listing_list">
                      <li class="highlighted">{{ booking.hotel.total }}</li>
                    </ul>
                  </div>					  					  
                </div>
              </div>
            </div>
            <!-- <div class="buttons-to-right"> <a href="#" class="button gray reject"><i class="sl sl-icon-close"></i> Cancel</a> </div> -->
          </li>
          
        </ul>
      </div>		  
    </div>
    <div class="col-md-12">
      <div class="footer_copyright_part">Copyright © 2022 All Rights Reserved.</div>
    </div>
  </div>
</div>
</div>
</div>

{% endblock content %}

templates/user_dashboard/dashboard.html
{% extends 'partials/dashboard_base.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="margin-top-0">
            <div class="row">
                <div class="col-lg-4">
                    <div class="utf_dashboard_block_part color-1">
                        <div class="utf_dashboard_ic_stat"><i class="fa fa-money"></i></div>
                        <div class="utf_dashboard_content_part utf_wallet_totals_item">
                            <h4>{{bookings.count}}</h4>
                            <span>Total Paid Bookings</span>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="utf_dashboard_block_part color-2">
                        <div class="utf_dashboard_ic_stat"><i class="sl sl-icon-wallet"></i></div>
                        <div class="utf_dashboard_content_part utf_wallet_totals_item">
                            <h4>${{ total_spent_to_display }}</h4>
                            <span>Total Spent</span>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="utf_dashboard_block_part color-3">
                        <div class="utf_dashboard_ic_stat"><i class="sl sl-icon-list"></i></div>
                        <div class="utf_dashboard_content_part">
                            <h4>$2050</h4>
                            <span>Wallet Balance</span>
                        </div>
                    </div>
                </div>

               
            </div>

            <div class="row">
               

                <div class="col-lg-12 col-md-12 mb-4">
                    <div class="utf_dashboard_list_box table-responsive recent_booking">
                      <h4>Recent Booking</h4>
                      <div class="dashboard-list-box table-responsive invoices with-icons">
                        <table class="table table-hover">
                          <thead>
                            <tr>
                              <th>#</th>
                              <th>Hotel Name</th>
                              <th>Total Rooms</th>
                              <th>Booking Date</th>
                              <th>Payment Status</th>
                              <th>View Booking</th>
                            </tr>
                          </thead>
                          <tbody>

                            {% for b in bookings%}
                            <tr>
                              <td>{{ forloop.counter }}</td>
                              <td>{{b.hotel }}</td>
                              <td>{{b.room.all.count}}</td>
                              <td>{{b.date}}</td>
                              <td><span class="badge badge-pill badge-primary text-uppercase">{{b.payment_status}}</span></td>
                              <td><a href="{% url 'user_dashboard:booking_detail' b.booking_id %}" class="button gray"><i class="fa fa-eye"></i> View</a></td>
                            </tr>
                            {% endfor %}

                            
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>


                 <div class="col-lg-12">
                    <div class="utf_dashboard_list_box invoices with-icons margin-top-20">
                        <h4>All Booking Invoices</h4>
                        <ul>
                            {% for b in bookings%}
                            <li><i class="utf_list_box_icon fa fa-paste"></i> {{ b.hotel.name }}<strong> <span
                                        class="paid">{{b.payment_status}}</span></strong> <a href="dashboard_invoice.html">Invoice</a><span class="date">
                                <ul>
                                    <li><span>Order Number:-</span> {{b.booking_id}}</li>
                                    <li><span>Date:-</span> {{b.date}}</li>
                                </ul>
                                <div class="buttons-to-right"> <a href="dashboard_invoice.html" class="button gray"><i
                                            class="sl sl-icon-printer"></i> Invoice</a> </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div> 
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="footer_copyright_part">Copyright © 2024 All Rights Reserved. <br>Developed by Olawuni Emmanuel Kayode</div>
    </div>
</div>
</div>
</div>
</div>
{% endblock content%}

templates/user_dashboard/profile.html
{% extends 'partials/dashboard_base.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="utf_dashboard_list_box margin-top-0">
            <h4 class="gray"><i class="sl sl-icon-user"></i> Profile Details</h4>
            <div class="utf_dashboard_list_box-static">
                <form method="POST" enctype="multipart/form-data">

                    {% csrf_token %}


                    <div class="edit-profile-photo" style="width:400px;" id="profile_image_preview"> <img src="{{ profile.image.url }}" alt="">
                    <div class=" change-photo-btn">
                        <div class="photoUpload"> <span><i class="fa fa-upload"></i> Upload Photo</span>
                            <input type="file" class="upload" />
                            {{ profileForm.image }}
                        </div>
                    </div>
                </div>
                <div class="my-profile">
                <div class="row with-forms">
                    <div class="col-md-6">
                        <label>Full Name</label>
                        {{ profileForm.full_name }}
                    </div>
                    <div class="col-md-6">
                        <label>Email</label>
                        {{ userForm.email}}
                    </div>
                    <div class="col-md-4">
                        <label>Phone</label>
                        {{ profileForm.phone }}
                    </div>

                    <div class="col-md-4">
                        <label>Address</label>
                        {{ profileForm.address }}
                    </div>

                    <div class="col-md-4">
                        <label>Country</label>
                        {{ profileForm.city }}
                    </div>

                    <div class="col-md-4">
                        <label>Country</label>
                        {{ profileForm.state }}
                    </div>

                    <div class="col-md-4">
                        <label>Country</label>
                        {{ profileForm.country }}
                    </div>

                </div>
            </form>
            </div>
            <button type="submit" class="button preview btn_center_item margin-top-15">Save Changes</button>
        </div>
    </div>
</div>
<div class="col-md-12">
    <div class="footer_copyright_part">Copyright © 2024 All Rights Reserved | Homifice </div>
    <div class="footer_copyright_part">Developed By Olawuni Emmanuel Kayode </div>
</div>
</div>
</div>

<script>
    let loadFie = function (event) {
        let output2 = document.getElementById('profile_image_preview');
        output2.src = URL.createObjectURL(event.target.files[0]);
        output2.onload = function () {
            URL.revokeObjectURL(output2.src) // free memory
        }
    }
</script>
{% endblock content %}